# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  IISWebsiteName: 'TiGets'

resources:
 pipelines:
     - pipeline: 'buildPipeline'
       project: 'TiGets'
       source: 'Build pipeline'
       branch: 'main'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'
    pool:
      vmImage: windows-latest
    
    jobs:
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'Windows.DESKTOP-CG3R92G'
      strategy:
       runOnce:
           deploy:
            steps:
                - checkout: none

                - download: 'buildPipeline'
                  name: 'DownloadBuildArtifacts'
                  displayName: 'Download Build Artifacts'
                  artifact: 'TiGets'
                
                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StopIIS'
                  displayName: 'Stop IIS website'
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StopWebsite'
                    StartStopWebsiteName: '${{ variables.IISWebsiteName }}'

                #- script: echo $(Pipeline.Workspace)\buildPipeline\AzureTestProject\RoundTheCode.AzureTestProject

                - task: IISWebAppDeploymentOnMachineGroup@0
                  name: 'DeployIIS'
                  displayName: 'Deploy IIS website'                
                  inputs:
                    WebSiteName: '${{ variables.IISWebsiteName }}'
                    Package: '$(Pipeline.Workspace)\buildPipeline\TiGets\TiGets.WebApp'
                    TakeAppOfflineFlag: true
                
                - task: IISWebAppManagementOnMachineGroup@0
                  name: 'StartIIS'
                  displayName: 'Start IIS website'                     
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'StartWebsite'
                    StartStopWebsiteName: '${{ variables.IISWebsiteName }}'